"""Add part field to TeacherCourse

Revision ID: 8458c2eab490
Revises: 4b6b249bc62c
Create Date: 2025-06-03 16:20:07.881696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8458c2eab490'
down_revision = '4b6b249bc62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part', sa.String(length=10), nullable=False, server_default='Full'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_course', schema=None) as batch_op:
        batch_op.drop_column('part')

    # ### end Alembic commands ###
