"""Add class_count and shared_callsign to Course model

Revision ID: 865344942ad1
Revises: 8458c2eab490
Create Date: 2024-03-19 12:34:56.789012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865344942ad1'
down_revision = '8458c2eab490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shared_callsign', sa.String(length=20), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE course SET class_count = 1 WHERE class_count IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('class_count',
               existing_type=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('shared_callsign')
        batch_op.drop_column('class_count')
    # ### end Alembic commands ###
